version: 2.1

orbs:
  node: electronjs/node@2.1.0

workflows:
  test:
    jobs:
      - node/test:
          name: test-<< matrix.executor >>-<< matrix.node-version >>
          matrix:
            alias: test
            parameters:
              executor:
                - node/linux
                - node/macos
                - node/windows
              node-version:
                - '20.9'
